package com.bilicute.spacetime;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
@SpringBootApplication
public class SpaceTimeApplication {

    public static void main(String[] args) {
        SpringApplication.run(SpaceTimeApplication.class, args);
    }

}
